version: "3.5"

services:
  mongo:
    image: mongo:6.0.1
    environment:
      MONGO_INITDB_ROOT_USERNAME: dtpl-db
      MONGO_INITDB_ROOT_PASSWORD: DTPLdb-2o24
    ports:
      - 27017:27017

  minio:
    image: minio/minio:RELEASE.2022-05-26T05-48-41Z
    environment:
      MINIO_ROOT_USER: 'AKIAIOSFODNN7EXAMPLE'
      MINIO_ROOT_PASSWORD: 'wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY'
    command: [ "server", "/data", "--console-address", ":9001" ]
    volumes:
      - minio:/data
    ports:
      - 9000:9000
      - 9001:9001

volumes:
  mongo:
  minio:
