version: "3.5"

services:
  mongo:
    image: mongo:6.0.1
    environment:
      MONGO_INITDB_ROOT_USERNAME: dtpl-db
      MONGO_INITDB_ROOT_PASSWORD: DTPLdb@2024!
    ports:
      - 27017:27017

volumes:
  mongo: